channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=23.3.1
- pip:
  - mlflow==2.11.3
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - packaging==23.1
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.3.0
  - scipy==1.12.0
name: mlflow-env
